### ISSUE TITLE
Mantis day: 11-09-2024

### ISSUE THREAD

**Issue by dccabanas** [MantisFEM/Mantis.jl#101]
Discussion topics:

- [x] MantisFEM/Mantis.jl#270 
- [x] MantisFEM/Mantis.jl#97
- [x] MantisFEM/MantisDev.jl#37 
- [x] MantisFEM/Mantis.jl#98 
- [x] MantisFEM/Mantis.jl#102 
- [x] Think of some low priority project/task for the BSc minor project in CSE, for example: (i) studying the paralelization of the assembly block, (ii)... other ideas? 
- [x] Discuss the organization of the code, e.g., `create_bspline_space` could be placed in a single file where all higher level functions are placed. The idea would be to have some kind of hierachical structure that goes from the most highlevel functions to the most lowlevel functions. If we mix both, then it becomes very difficult to find anything.
- [x] Discuss FEM spaces, extraction coefficients in some but not in others, can we make them all work in the same way?
- [x] Discuss updates made in MantisFEM/Mantis.jl#106  (it seems like too much has changed but it's less scary than that, I promise!)
