### ISSUE TITLE
Mantis day: 23-10-2024

### ISSUE THREAD

**Issue by dccabanas** [MantisFEM/Mantis.jl#138]
@apalha, @dtoshniwal , @J15525 : Add your topics for discussion this week here

**Discussion topics**:
- [x] Wedge and other open pull requests so we can merge: MantisFEM/Mantis.jl#132, MantisFEM/Mantis.jl#136, MantisFEM/Mantis.jl#133
- [x] How we want to handle weak formulations: MantisFEM/Mantis.jl#130 
- [x] The way to handle topology: MantisFEM/MantisDev.jl#32 
- [x] Unfinished topics from the last meeting: MantisFEM/Mantis.jl#135 

**Things to do**
- Add more tests to wedges: analytical and properties.
- Investigate logging and verbosity levels
- Merge wedge product pull request after tests
- Make pull request for multivalued forms
- Test the performance penalty of using a weak form struct that accepts NTuple arguments
- Generalize assembly based on expression rank (E.g., for eigenvalue problems, the RHS is expression rank 1 not 0)
- Look at eigenvalue packages that allow sparse matrices (e.g., https://github.com/nep-pack/NonlinearEigenproblems.jl)
- Add pre-allocation in evaluate(AbstractFiniteElementSpaces) to avoid problems with Memoization
- Look at MeshCore.jl for topological information
