### ISSUE TITLE
Meeting 04/12/2024

### ISSUE THREAD

**Issue by dccabanas** [MantisFEM/Mantis.jl#161]
@apalha @dtoshniwal @J15525 
- [x] Performance issues with mixed form spaces and mixed weak forms - when do we go ahead with this choice?
- [x] Rewrite TensorProductSpaces according to MantisFEM/Mantis.jl#127 @dccabanas 
- [x] Merge MultivaluedForms @apalha @dtoshniwal 
- [x] Quadrature example/new tests @J15525 
- [x] Merged updated MantisFEM/Mantis.jl#130 @apalha @dtoshniwal 
- [ ] Add analytical 2-forms MantisFEM/Mantis.jl#270 @apalha 
- [ ] Add code coverage @apalha 
- [ ] Add a new module for every testset @everyone
---
Next steps
---
- [ ] Freeze new features to work on clean-up (documentation, tests, etc...) @everyone 
- [ ] Separating evaluations for plotting (e.g., loops over all elements and evaluating and storing data at points inside the elements) from writing to VTK. Reason being that we can then reuse the outputs of the former for exporting to TikZ or plotting in Makie, ....
- [ ] Multipatch geometries + interface spaces + boundary conditions
- [ ] Topology stuff @everyone
