### ISSUE TITLE
Meeting on 11 December 2024

### ISSUE THREAD

**Issue by J15525** [MantisFEM/Mantis.jl#165]
The overview for Wednesday's meeting. Add your topics to discuss.

- [x] Discuss the mergeability of #130.
- [ ] Todo's in the repo.
- [ ] Discuss the structure of Mantis.
    - Repo structure? e.g.:
    - https://github.com/matiassingers/awesome-readme?
    - https://github.com/JuliaBesties/BestieTemplate.jl?
- [ ] Discuss #164 if there is any news.
- [ ] What do we want to do after the Christmas break? Discuss goals and planning.
- [ ] Left-overs from #161.
- [ ] Github account free minutes usage: run assembler tests randomly?
