### ISSUE TITLE
Test, test, test

### ISSUE THREAD

**Issue by J15525** [MantisFEM/Mantis.jl#87]
We still have to add a lot of test for the new code from the past weeks. This is a list of what we need to test still. Feel free to add to it.

- [ ] Check if the crazy mesh works for the mixed (and non-mixed for completeness) Poisson problems as currently running.
- [ ] Add tests for the inner products.
- [ ] Add tests for the L2 projection assembler.
- [ ] Add convergence tests for the assembled test problems.
    - [ ] Some old test files for both the L2 and convergence tests are still there, but they will need to be adapted to the new interfaces.
- [ ] Add non-constant forcing functions to the test cases (once possible, or by finding the coefficients by using old inner product functionality).
- [ ] With reference to #64 (maybe we should close that one, as all that info is here now), the geometry (especially Jacobians and metric?) tests need to be extended.
- [x] Add tests for the Hodge star. (this is done in multivalued-forms, which is(is being) merged) [apalha]
- [ ] Add tests for the sharps and flats.
- [ ] Sharp and push-forward tests such as (see also #83):
    - initialize analytical form field in physical coordinates,
    - evaluate the pulledback analytical form field, then sharpen and pushforward those evaluations,
    - check that the result of 2. corresponds to the analytical form field in physical coordinates.
 - [x] Add tests for Quadrature by testing integral computations.
- [ ] Add more tests for exterior derivative [apalha]
        - The test file for exterior derivative was doing some tests on the Hodge, there was nothing on exterior derivative. I removed what was not relevant and added basic tests to the exterior derivative: d(constant) = 0. I would check a few cases for correctness and then just copy paste the data and make a test that just compares against that. This is what in the end we do for many of the checks we perform to make sure a function is working properly, so I propose we just do that, besides any other functionality tests.

We can also add this (again #64):
- [x] Add codecov button to show how much (or little) code is actually being tested. Added in #213.
