### ISSUE TITLE
Assembly and error computation updates

### ISSUE THREAD

**Issue by J15525** [MantisFEM/Mantis.jl#95]
After the bigger form-related updates and the closing of #85 and #88, some updates for the assembly and error computations are in order. These are listed here.

Error-related:
- [x] Error 'assembler': Implement H1 error computation.
- [x] Error 'assembler': Evaluation points for Linf error computation. (Either add evenly spaced quad rule that can be used for this (but is still an actual quadrature rule), or add an extra/optional argument to provide a (probably tuple of) evaluation points). Adding a quadrature rule may be nice here.
- [ ] Error 'assembler': 'local' L2 error that can be plotted as volume form. This requires the wedge, see #81.
- [x] Move the error computation functions to a separate file (module even?) as they have nothing to do with assembly any more. They are now pure analysis (which may be a new module). Completed in #209.

Assembly:
- [x] Global assembler: Turn the current global assembler into a normal function. The callable struct is not necessary at this stage. A conventional function is easier to use. Completed in #107.
